### ISSUE TITLE
Sumaform RPMs

### ISSUE THREAD

**Issue by srbarrios** [uyuni-project/sumaform#501]
Currently we use master branch to prepare our test environments in CI.
It implies to checkout the repository every time and uncertainty about the behaviour of latest commit.
I propose to have versions of Sumaform and generate release packages (rpm?)
So we install them in our Jenkins Slaves, reducing checkouts of the repository and relying on a concrete version of Sumaform for all our job executions.

**Comment by srbarrios** [comment]
@moio @juliogonzalez you could be interested on that one :factory:

**Comment by juliogonzalez** [comment]
Building RPMs is possible, yes.

And strictly speaking we won't need "sumaform releases". We can just have the RPM building at OBS with two stages. First one will build the package for each GitHub change. Second will build the package when we run `osc release` to promote a package.

So no changes would be needed at sumaform repository.

**Comment by moio** [comment]
@juliogonzalez +1

Alternatively we could have a QA-approved/hardened/specific branch which is only changed by QA when QA has a need, and otherwise does not really evolve - and skip RPMs completely.

This is simpler to implement (no OBS), but less end-user-friendly. I am open to name suggestions for this branch.

@srbarrios also suggested the other way round - moving development to a `develop` branch and keep `master` as the "QA-approved" branch. This has the disadvantage of changing the meaning of `master` as it is used today - there seems to be no consensus out there about the meaning of `master` vs `develop` - so that's my least preferred option.

**Comment by srbarrios** [comment]
Awesome, I like that approach.

**Comment by srbarrios** [comment]
@moio @juliogonzalez so, I think we have some agreement :)
Let's do like @juliogonzalez proposed? Could you help me on that @juliogonzalez ?

**Comment by juliogonzalez** [comment]
@srbarrios, I can, but let's created an EPIC and cards so we can schedule the work :-)

**Comment by juliogonzalez** [comment]
This is ready at https://build.opensuse.org/project/show/systemsmanagement:sumaform:package:development and https://build.opensuse.org/project/show/systemsmanagement:sumaform:package :-)

**Comment by moio** [comment]
Is the plan to use packaged sumaform only for the Uyuni testsuite or do we want to recommend it for general use?

**Comment by juliogonzalez** [comment]
The plan was to use it for the SUSE Manager testsuite, in particular this was requested to test the unreleased maintenance updates (@srbarrios). But IMHO we should the released package everyone and recommend it in all cases where the user can install RPMs (in the future maybe we should consider creating DEB packages as well)
