### ISSUE TITLE
Why we load all SLS repos in all our modules?

### ISSUE THREAD

**Issue by srbarrios** [uyuni-project/sumaform#959]
We have this folder https://github.com/uyuni-project/sumaform/tree/master/salt/repos where we organize the repositories needed for each kind of module (or this organization in different files have another meaning?)

But then in the server we load all the files inside repos folder:
https://github.com/uyuni-project/sumaform/blob/master/salt/server/init.sls#L1-L2

Same in proxy:
https://github.com/uyuni-project/sumaform/blob/master/salt/proxy/init.sls#L1-L2

Same everywhere else, like in a minion:
https://github.com/uyuni-project/sumaform/blob/master/salt/minion/init.sls#L1-L2

Shouldn't we instead, only load the specific sls file?
For example, on the server, use:
```
include:
  - repos.server
```

As we do now, we can have hidden issues, see for instance:
https://github.com/uyuni-project/sumaform/blob/master/salt/repos/server.sls#L176-L186
https://github.com/uyuni-project/sumaform/blob/master/salt/repos/proxy.sls#L128-L138

Where we have the same defined repositories twice. So depending the other we load these sls files, and the URL defined on those repos, it could be overwritten differently. In that case we have the same URLS, but it's a source of issues from my point of view.

**Comment by rjmateus** [comment]
We need to load the root folder, since some code needs to be shared across all roles [0] [1].
At the beginning of each role specific file, we check if the machine has that role or not [2]. Since we are checking the machine role, no duplicates should exist.
We maybe can do the check at the init.sls [3], instead of doing it inside the specific files.

for example:
```
include:
  {% if not grains.get('additional_repos_only') %}
  - repos.default
  - repos.minion
  - repos.proxy
{% if 'server' in grains.get('roles') %}
  - repos.server
{% endif %}
  - repos.testsuite
  - repos.virthost
  - repos.tools
  {% endif %}
  - repos.additional
```
So, each machine always applies, from inside `repos` dirctory the following sls files `init.sls` and `additional.sls`. And then other depending on the machine configuration.
Another example, one minion may need to apply:  `init.sls`, `additional.sls`,  `minion.sls` and `testsuite.sls`.

[0] https://github.com/uyuni-project/sumaform/blob/master/salt/repos/default.sls
[1] https://github.com/uyuni-project/sumaform/blob/master/salt/repos/server.sls#L1
[2] https://github.com/uyuni-project/sumaform/blob/master/salt/repos/server.sls#L1
[3] https://github.com/uyuni-project/sumaform/blob/master/salt/repos/init.sls#L3-L9

**Comment by srbarrios** [comment]
Thanks for the explanation! Closing :)
